### ISSUE TITLE
Grass not Dropping Seeds

### ISSUE THREAD

**Issue by Edgareredra** [TheGoldCrayon/RopesMod#2]
Hello,

I'm playing on Minecraft version 1.15.2 on Forge version 31.1.14 and I'm running mods that also affect the drops of grass; such as Simple Farming. It seems that whenever I load Ropes mod with any mod that affects grass drops it locks the drops of grass entirely. 

I've tested this mod by running it alone, and the others as well; and in these cases, they run just fine. However, running them together is 100% the issue. I suppose it could be the Forge version that I'm running or the issue may lie with the other mod, but I thought I'd make this issue public if no one has brought it up yet.

**Comment by TheGoldCrayon** [comment]
Hmmm. I'm not sure. I honestly don't know if the way I add seeds to the drop table of grass is the best way, but it was one of the few I found that I understood. I'll add a recipe to make the hemp seeds for cases like this.

**Comment by Edgareredra** [comment]
Sounds great! Thanks for the reply. I don't really know about coding or modding, but perhaps there's a way to make the seeds not drop from grass at all in configs so that it doesn't lock all the grass drops?

If it's hard or not possible it's cool. Really appreciate the mod and your work regardless.

**Comment by TheGoldCrayon** [comment]
crafting recipe for seeds has been added in 1.2.0
